### ISSUE TITLE
GitHub API rate limiting is a challenge

### ISSUE THREAD

**Issue by kwurst** [StoneyJackson/scramblewords.py#4]
I'm having problems with the GitHub API rate limit. Running it on LICENSE (GPL3) at 10% produces about 460 issues, and I can't get them all added before hitting the abuse limit. I'm going to try it on 5% next (about 230) and see if they get added...

**Comment by kwurst** [comment]
And it takes a while, since I've throttled it to 3 seconds per issue

**Comment by StoneyJackson** [comment]
Faster than me :)

-- 
Stoney Jackson
Sent with Airmail

On February 13, 2017 at 4:31:33 PM, Karl R. Wurst (notifications@github.com)
wrote:

And it takes a while, since I've throttled it to 3 seconds per issue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StoneyJackson/git-twiddler/issues/4#issuecomment-279528957>,
or mute the thread

**Comment by kwurst** [comment]
Yeah, but you don't really want to sit and wait the 11.5 minutes it takes to add 230 issues.

**Comment by kwurst** [comment]
Successfully uploaded 238 issues with a 3 sec delay between each. It took 13 minutes, 5 seconds.
I'm going to consider this closed for now, until someone has a difficulty with trying to upload more issues.
